### ISSUE TITLE
Search screens footers missing CCA homepage link

### ISSUE THREAD

**Issue by lrayshel** [cca/millennium_catalog#19]
urls: http://library.cca.edu/search~S2, http://library.cca.edu/screens/thesis_search.html
screens: /opacmenu_s2.html, /thesis_search.html

basic search, theses footer:
![basic-search-footer_12-2014](https://cloud.githubusercontent.com/assets/10122362/5421407/38fe6eb6-8218-11e4-8377-1f0f56c2ef43.png)
advanced search footer:
![advanced-search-footer_12-2014](https://cloud.githubusercontent.com/assets/10122362/5421411/439ecd84-8218-11e4-95d2-3586285524b3.png)

**Comment by phette23** [comment]
These should be fixed in staging now.
