### ISSUE TITLE
Search filters different in drop down menu on home page and in basic search page 

### ISSUE THREAD

**Issue by lrayshel** [cca/millennium_catalog#25]
1. "LCSH" on homepage and "Subject" on Basic Search page (same screen, different string). Use "Subject" on homepage or ok as is?
2. More Search filters on Basic Search page. Make consistent or ok as is?

Screenshots:
![screen shot 2014-12-17 at 3 27 52 pm](https://cloud.githubusercontent.com/assets/10122362/5481099/64cdd648-8601-11e4-81fb-2c9da0e28132.png)
![screen shot 2014-12-17 at 3 28 12 pm](https://cloud.githubusercontent.com/assets/10122362/5481100/676c7666-8601-11e4-9d3d-8b21adb73a13.png)

**Comment by phette23** [comment]
I changed "LCSH" to the more-friendly "Subject" on the main website and reordered the filters to match.
I don't feel like either local call no. or ISBN/ISSN is worth adding at the moment. Most searches are for keywords anyways, I'd rather offer a short list of understandable options than a comprehensive but inscrutable one.
