### ISSUE TITLE
book jacket icons broken in new material library opac display pages

### ISSUE THREAD

**Issue by lrayshel** [cca/millennium_catalog#26]
1. from Basic Search screen, enter keyword "fiber" and limit to "New Materials Library"
(search results: http://library.cca.edu/search~S6/?searchtype=Y&searcharg=fiber&searchscope=6&SORT=D&extended=0&SUBMIT=Search&searchlimits=&searchorigarg=dfiber)
2. scroll down results and note broken images - fix? ok as is?

Notes: did a couple of different keyword searches in materials library and see multiple broken images. Random searches in other parts of catalog don't reveal broken links so consistently.

**Comment by phette23** [comment]
I've made this appear a lot better by working around the dozens of broken image icons that were loading, so I'm going to close the issue. The solution is for the Materials Library to finish uploading the scanned images of material samples to the "nml-images" folder on the libraries' web server. The more that are added, the more items that will have images in their search results & item summary pages.
