### ISSUE TITLE
Link to ArtBibliographies Modern (ProQuest) to general Proquest interface

### ISSUE THREAD

**Issue by lrayshel** [cca/millennium_catalog#31]
All links to ArtBibliographies Modern on library Website go to Proquest launch page (http://search.proquest.com/?accountid=30962&selectids=1007425,1007425) with list of several subject area links rather than to ArtBib, directly (http://search.proquest.com/artbibliographies?accountid=30962). 

OK as is or provide direct link to ArtBibliographies Search screen (similar to other db links) and consider adding links to additional Proquest dbs on Website?

On review, the search screen has been delimited to just the artbib db, so may be ok as is, but I found it a bit confusing.

**Comment by phette23** [comment]
When I click either of those links, the pages that appear are identical. How is going into ArtBib directly different? With either I see that I'm searching two ProQuest databases, ArtBib and DAAI, so maybe that needs to be corrected. I'm guessing that the `selectids=…` portion of the URL specifies which databases are selected for searching and that specifying solely the ArtBib ID is equivalent to going to search.proquest.com/artbibliographies.

**Comment by lrayshel** [comment]
ArtBib does have its own landing page, but I see that the link above resolves to the same proquest landing page, w/ 1 db selected (the artbib that the selectids= specifies). Here's a screenshot of the ArtBib landing page: 

![screen shot 2015-01-14 at 1 30 37 pm](https://cloud.githubusercontent.com/assets/10122362/5748082/fd78834c-9bf1-11e4-8e30-551efd3d9bba.png)

Perhaps more to the point might be the question of whether the other proquest dbs to which we have access get called out in the a-z list?

**Comment by phette23** [comment]
ProQuest must be using cookies to store information about the last set of databases you searched; when I click that 2nd link, I don't see the landing page you posted but a generic PQ search screen with 2 databases selected. If I select just ArtBib, then I see that screen.

Either way, we want links going to the specific db they advertise. If this is a problem all over the library website it may take a little while to track down all the links and change them.

**Comment by lrayshel** [comment]
reviewing this again: 
http://search.proquest.com/artbibliographies/arts/fromDatabasesLayer?accountid=30962 
is a slightly different link (than the one above) that (for me) goes directly to the art bib home page in proquest. Does it work for you, as well? (I cleared my cache and then tested it and it resolved to arts bib home page).

Other Proquest links on our Website: 
- DAAI works as expected (resolves to db's home pg w/in proquest): 
https://proxy.cca.edu/login?url=http://search.proquest.com/daai?accountid=30962

Finally, it appears that we have a subscription to multiple proquest db's, not just arts bib and daai - I think we should add the link to the search page for multiple db's to the a-z list as its own entry...
https://proxy.cca.edu/login?url=http://search.proquest.com/?accountid=30962&selectids=1007425,1007425

![screen shot 2015-02-12 at 4 14 13 pm](https://cloud.githubusercontent.com/assets/10122362/6179910/e89ef738-b2d2-11e4-9213-e88ddf66c8ca.png)

**Comment by phette23** [comment]
You're right—those links of form "http://search.proquest.com/{{database name}}" seem to be somehow more persistent than what we were using before. I've changed over ArtBibs to use that type of link but the DAAI was already set up that way.

Changes only on the staging catalog for now. Let me know if you spot similarly-structured links on the main website; I'm going to change over the ones on the home page & online resources pages, but that may not catch all of them.

**Comment by lrayshel** [comment]
will do.
